---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de StorageGRID
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Descubra los sistemas StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Gestione los sistemas StorageGRID
    entries:
    - title: Vea sus sistemas StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Utilice los servicios de datos de NetApp con StorageGRID
      url: "/task-enable-data-services.html"
    - title: Eliminar un entorno de trabajo
      url: "/task-remove-storagegrid.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
