---
sidebar: sidebar 
permalink: task-enable-data-services.html 
keywords: storagegrid, cloud sync, cloud backup, backup, back up data, tier data, data tiering, tiering to storagegrid 
summary: Cuando detecte un sistema StorageGRID en BlueXP , podrá usar los servicios de datos de NetApp para backups, organización en niveles y sincronización de datos. 
---
= Utilice los servicios de datos de NetApp con StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando detecte un sistema StorageGRID en BlueXP , podrá usar los servicios de datos de NetApp para backups, organización en niveles y sincronización de datos.

* Utiliza el backup y la recuperación de BlueXP para hacer backup de datos desde tus sistemas ONTAP on-premises en el almacenamiento de objetos en tus sistemas StorageGRID de NetApp.
+
Para empezar, ve al lienzo de BlueXP y arrastra y suelta un entorno de trabajo de ONTAP on-premises en tu entorno de trabajo de StorageGRID.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html["Obtenga más información acerca de la realización de backups de datos de ONTAP en las instalaciones en StorageGRID"^]

* Utiliza la organización en niveles de BlueXP  para organizar automáticamente los datos inactivos desde clústeres de ONTAP on-premises a StorageGRID.
+
Para empezar, ve al lienzo de BlueXP y arrastra y suelta un entorno de trabajo de ONTAP on-premises en tu entorno de trabajo de StorageGRID.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-storagegrid.html["Obtenga más información sobre la organización de datos en niveles desde clústeres de ONTAP en las instalaciones hasta StorageGRID"^]

* Utiliza la copia y sincronización de BlueXP para sincronizar los datos que se encuentren en un sistema StorageGRID o desde él.
+
Para empezar, ve al lienzo de BlueXP y arrastra y suelta el entorno de trabajo de origen en el entorno de trabajo de destino. StorageGRID puede ser el origen o el destino.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["Obtén más información sobre la copia y sincronización de BlueXP"^]


